import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ColorModeSwitcher from '../src/components/ColorModeSwitcher'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Classroom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
          <ColorModeSwitcher justifySelf="flex-end" />



      </header>
    </div>
  )
}

export default Home
